export const BOOK_CHAPTERS = [
  {
    id: 'ch1',
    title: 'Chapter 1',
    subtitle: 'Creating the Robot Friends',
    chapterKey: 'Ch1',
    blocks: [
      { type: 'slot', slot_id: 'ch1-1', order_index: 1, label: 'Jackie tippy-toeing into kitchen with arms full of treasures — turquoise tin, bagpipe, tea cozy, woolly sweater, shortbread tins' },
      { type: 'text', content: 'One rainy Scottish morning, the rain tapped (pat-pat-patter) on the roof. Inside the cozy kitchen, Jackie Roo tippy-toed in, arms overflowing with treasures — a turquoise tin, an old bagpipe, a flower-speckled tea cozy, Grandma\'s woolly sweater, and shortbread tins going (clinkety-clink!) with every step.' },
      { type: 'slot', slot_id: 'ch1-2', order_index: 2, label: 'Mum and Jackie crafting Scotch Bot — polishing golden medallion, adding bell, swirly eyes glowing' },
      { type: 'text', content: '"Time for magic!" she declared. "Let\'s make robots!" Mum looked up from her iPad, coffee paused mid-sip. "What a brilliant idea, my clever girl!" Together they built Scotch Bot first — one eye swirly, one sparkly, topped with a golden medallion. (zing-zing!) His turquoise tummy glowed like starlight.' },
      { type: 'slot', slot_id: 'ch1-scotch', order_index: 3, label: 'Scotch Bot birth panel — zing-zing!' },
      { type: 'text', content: 'From tins and springs and swirly things — zing-zing! — Scotch Bot!' },
      { type: 'slot', slot_id: 'ch1-bagpipe', order_index: 4, label: 'Bagpipe Bot birth panel — toot-toot-wheeze!' },
      { type: 'text', content: 'From tartan ribbons and a checkered hat — toot-toot-wheeze! — Bagpipe Bot!' },
      { type: 'slot', slot_id: 'ch1-tess', order_index: 5, label: 'Tea Cozy Tess birth panel — ping!' },
      { type: 'text', content: 'From a flower-speckled cozy and two silver spoons — ping! — Tea Cozy Tess!' },
      { type: 'slot', slot_id: 'ch1-woolie', order_index: 6, label: 'Woolie Watt birth panel — zip-zap!' },
      { type: 'text', content: 'From Grandma\'s woolly sweater and a crackle of static — zip-zap! — Woolie Watt!' },
      { type: 'slot', slot_id: 'ch1-sam', order_index: 7, label: 'Shortbread Sam birth panel — munch-munch-happy-lunch!' },
      { type: 'text', content: 'From shortbread tins and cookie crumbs — munch-munch-happy-lunch! — Shortbread Sam!' },
      { type: 'slot', slot_id: 'ch1-row-before', order_index: 8, label: 'PAGE TURN (1 of 2) — Mum and Jackie admiring all five robots in a cheerful row, stormy rain outside, robots perfectly still' },
      { type: 'pageturn' },
      { type: 'slot', slot_id: 'ch1-row-after', order_index: 9, label: 'PAGE TURN (2 of 2) — Robots ERUPT the moment Mum leaves the room — sparks flying, Woolie Watt crackling, Tess steaming, Jackie spinning' },
      { type: 'text', content: 'Five wonderful robot friends sat in a cheerful row. "Time for an adventure!" Jackie declared, fetching the red wagon. (squeak-squeak!)' },
    ],
  },
  {
    id: 'ch2',
    title: 'Chapter 2',
    subtitle: 'The Oak Tree Adventure',
    chapterKey: 'Ch2',
    blocks: [
      { type: 'slot', slot_id: 'ch2-wagon', order_index: 10, label: 'Jackie pulling red wagon through misty Scottish park toward the wise old oak tree' },
      { type: 'text', content: 'The misty Scottish morning wrapped the world in a soft grey blanket. Jackie Roo skipped ahead, her kangaroo onesie swishing with every bounce. Past the flower shop with its colourful window boxes. Through the creaky iron gates of the park. Until finally, there stood the wise old oak tree.' },
      { type: 'slot', slot_id: 'ch2-puddle', order_index: 11, label: 'Scotch Bot spotting the muddy puddle — golden medallion whirling, magnificent SPLISH-SPLASH' },
      { type: 'text', content: 'Scotch Bot\'s turquoise tummy caught a stray beam of light. (whizz-beep!) He spotted something wonderful — a magnificent muddy puddle shimmering nearby. (splish-splash-splendidy-splash!) He jumped right in. Mud flew in joyful arcs. His golden medallion whirled wildly. (zing-zing-ZING!)' },
      { type: 'slot', slot_id: 'ch2-orchestra', order_index: 12, label: 'All robots and Jackie in the muddy puddle — Jackie conducting with stick wand, golden peek-a-boo sun' },
      { type: 'text', content: 'Jackie Roo could resist no longer. She hopped right into the middle of the muddy orchestra. She found a perfect stick and turned it into a magic wand. Rising up and down on her tippy-toes, she conducted her robot friends.' },
      { type: 'slot', slot_id: 'ch2-oak', order_index: 13, label: 'Jackie pressing hands on the wise old oak tree — glowing acorn lantern, puddle reflection' },
      { type: 'text', content: 'Back in the cozy kitchen, Mum whispered, "The real magic lives in that old oak, love. It lends its wonder to your adventures whenever you\'re beneath its branches." Jackie hugged her oak twig wand tightly, and smiled.' },
    ],
  },
  {
    id: 'ch3',
    title: 'Chapter 3',
    subtitle: 'The Journey to the Secret Rainbow Cave',
    chapterKey: 'Ch3',
    blocks: [
      { type: 'slot', slot_id: 'ch3-bandit', order_index: 14, label: 'Scotch Bot with cheeky muddy bandit mask — Jackie secretly packing surprise picnic with rainbow trout sandwiches and Swiss chard' },
      { type: 'text', content: 'Jackie spotted a muddy smear across Scotch Bot\'s turquoise face. It looked exactly like a cheeky bandit\'s mask. "He looks like a wee bandit!" she cried. "Let\'s find the Secret Rainbow Cave behind the waterfall!"' },
      { type: 'slot', slot_id: 'ch3-cave', order_index: 15, label: 'Rainbow cave interior — singing colours, Jackie twirling with wand, robots dancing' },
      { type: 'text', content: 'At the waterfall, Scotch Bot dived straight in with a joyful (plop!) His glow formed a beautiful rainbow bridge. Inside, singing colours hummed gentle melodies. Red glowed warm. Orange tickled. Yellow sang happy. Green whispered peace. Blue cooled. Indigo dreamed. Violet sparkled mystery.' },
      { type: 'slot', slot_id: 'ch3-picnic', order_index: 16, label: 'Rainbow cave picnic feast — Tess ladling rainbow carrot soup, everyone mid-feast and laughing' },
      { type: 'text', content: '"You planned this!" said Scotch Bot, delighted. "Obviously," said Jackie. Scotch Bot\'s muddy mask gently fell away with a soft (plink) into the clear pool below. He gave a happy zing-zing! as his familiar turquoise face shone again.' },
    ],
  },
  {
    id: 'ch4',
    title: 'Chapter 4',
    subtitle: 'The Whispering Windship',
    chapterKey: 'Ch4',
    blocks: [
      { type: 'slot', slot_id: 'ch4-windship', order_index: 17, label: 'Jackie blowing brass whistle — dragonfly-wing windship hovering above in the mist' },
      { type: 'text', content: 'Jackie bounded into the kitchen clutching the brass whistle she had found among the rainbow pebbles. (tweet-toot!) A magnificent windship appeared outside the window. Its sails shimmered like dragonfly wings glowing in the mist.' },
      { type: 'slot', slot_id: 'ch4-storm', order_index: 18, label: 'Transformed playground ship soaring — dramatic Storm King battle, robots defending' },
      { type: 'text', content: 'A kind whispering voice drifted from the sails. "I have words but cannot speak. I have leaves but am not a tree. What am I?" "A book!" The mist parted. Until suddenly the Storm King swooped in. Jackie steered the windship bravely into pursuit, wand held high.' },
      { type: 'slot', slot_id: 'ch4-return', order_index: 19, label: 'Ship descending to playground at twilight — bottled cloud, robots humming lullaby, sleepy Jackie' },
      { type: 'text', content: 'The Cloud Keeper presented a wondrous gift: a bottled cloud that released a gentle (puff-puff). The robots hummed a tender new lullaby beneath the twinkling stars. Jackie\'s boots whispered softly of even more adventures yet to come.' },
    ],
  },
  {
    id: 'ch5',
    title: 'Chapter 5',
    subtitle: 'The Woolly Goalkeeper',
    chapterKey: 'Ch5',
    blocks: [
      { type: 'slot', slot_id: 'ch5-march', order_index: 20, label: 'Jackie and all five robots trooping across the back garden — terracotta pot goalposts ahead' },
      { type: 'text', content: '"To the pitch!" Jackie announced. They trooped across the garden in a cheerful line — until Jackie stopped and looked down. No ball. She checked behind the rose bush. She checked under the bench. She checked inside the red wagon. Nothing. "Hmm," said Jackie.' },
      { type: 'slot', slot_id: 'ch5-woolie-knits', order_index: 21, label: 'Woolie Watt knitting the teal-and-gold wool ball — sparks from orange wire hair — click-click-klink!' },
      { type: 'text', content: 'Woolie Watt sat himself down, crossed his legs, and produced two long knitting needles from somewhere inside his purple sweater. (click-click-klink!) Slowly, steadily, a round lumpy ball of thick wool grew in his lap — teal and gold and a little bit wonky. "It\'s brilliant," said Jackie.' },
      { type: 'slot', slot_id: 'ch5-goalkeeper', order_index: 22, label: 'Scotch Bot the unbeatable goalkeeper — feet planted, arms spread, left eye swirling, chin lifted' },
      { type: 'text', content: 'Scotch Bot marched into goal without being asked. "I am unbeatable," he said cheerfully. Jackie ran and kicked with a magnificent THWUMP. Three rounds they played. Four. Five. The wool ball bobbled in a satisfying unpredictable way that made everyone laugh every single time.' },
      { type: 'slot', slot_id: 'ch5-eye-lost', order_index: 23, label: 'Commotion! Scotch Bot standing still, one eye socket empty — everyone frozen, looking at the grass' },
      { type: 'text', content: 'Then Scotch Bot stood very still. Where his left eye had been, there was now just a small round empty socket. He blinked. Or rather, he winked — because he had no choice in the matter. "Ah," he said. They searched. No eye.' },
      { type: 'slot', slot_id: 'ch5-bagpipe-bottle', order_index: 24, label: 'Bagpipe Bot at the recycling bin — holding up dark glass bottle with great dignity' },
      { type: 'text', content: 'Bagpipe Bot marched with great purpose to the recycling bin, reached in, and produced a dark glass bottle. On the back, still clinging on, was a round gold wax seal — thick and raised and gleaming. He held it out without a word.' },
      { type: 'slot', slot_id: 'ch5-eye-fixed', order_index: 25, label: 'Jackie on very tippy-toes, tongue out in concentration, pressing gold seal onto Scotch Bot\'s eye socket' },
      { type: 'text', content: 'Jackie rose on her very tippy-toes. Tongue poking out in absolute concentration, she pressed the gold seal carefully onto Scotch Bot\'s empty socket. (tap) It sat perfectly. Round and gold and gleaming, like it had always been there. "Good as new," she said softly.' },
      { type: 'slot', slot_id: 'ch5-tess-finds', order_index: 26, label: 'Tea Cozy Tess holding up the woolly ball — Scotch Bot\'s red spiral eye embedded in it. Tess mid-laugh — ting-a-ting-ding!' },
      { type: 'text', content: 'Tea Cozy Tess picked up the woolly ball and turned it over. There, pressed snugly into the teal and gold wool, was Scotch Bot\'s old eye, perfectly embedded, staring back at them. "It seems," she said, "he really did keep his eye on the ball."' },
      { type: 'slot', slot_id: 'ch5-pouch', order_index: 27, label: 'Jackie peeling the red spiral eye off the wool ball, tucking it into her kangaroo pouch' },
      { type: 'text', content: 'Jackie peeled Scotch Bot\'s eye carefully from the wool and tucked it into her front pouch with a satisfied nod. Then she looked up. The sky had turned the same grey as the stone wall. A small roll of thunder rumbled softly overhead. "Oh! I almost forgot!"' },
      { type: 'slot', slot_id: 'ch5-flowers', order_index: 28, label: 'Jackie picking wildflowers — Mum\'s face visible through the warm cottage window, watching with a tender smile' },
      { type: 'text', content: 'PIT-PAT-PATTER-PATTER-PAT-PAT-PAT!! The sky absolutely opened. "Single file!" shouted Jackie. "Biggest puddle! Everyone gets a turn!" Nobody argued. SPLOOOSH! SPLOOOSH! SPLOOOSH! SPLOOOSH! SPLOOOSH! SPLOOOOOOOOSH!!' },
      { type: 'slot', slot_id: 'ch5-puddle-grid', order_index: 29, label: 'Six-panel puddle jump grid — each character taking their turn in the pouring rain' },
      { type: 'text', content: 'Afterwards, Jackie gathered them all up in Mum\'s big tartan blanket — five soggy, muddy, wonderful robots wrapped in soft warm folds, arms and antennae poking out every which way. She carried them all inside, dripping and beaming.' },
      { type: 'slot', slot_id: 'ch5-doorway', order_index: 30, label: 'Jackie handing muddy robot bundle to Mum — treasure basket glowing on entryway floor, yellow door open behind' },
      { type: 'text', content: 'Mum smiled — warmly, with just a little grit. Under her breath, very quietly, she said — "I wish there was a cleaning fairy."' },
      { type: 'slot', slot_id: 'ch5-cleaning-fairy', order_index: 31, label: "What's a cleaning fairy? — yellow door, Jackie looking up, treasure basket glowing on the floor" },
      { type: 'text', content: '"Once upon a time," said Jackie. Mum laughed. Mum ran a deep warm bath. Jackie pressed Scotch Bot\'s spare swirly eye onto the rubber duck. She held it up with both hands. "Mum! Meet Quack Bot!" And Mum laughed. Properly. The kind that takes over.' },
      { type: 'slot', slot_id: 'ch5-quackbot', order_index: 32, label: 'Jackie holding Quack Bot triumphantly — Mum laughing beside the tub, rainbow bubbles everywhere' },
    ],
  },
  {
    id: 'finale',
    title: 'Finale',
    subtitle: 'Wordless Rocking Scene',
    chapterKey: 'Finale',
    blocks: [
      { type: 'slot', slot_id: 'finale', order_index: 33, label: 'Mum rocking Jackie in the armchair — Quack Bot hugged tight, all five robots on the windowsill in the rain watching over them' },
    ],
  },
];