export const BOOK_CHAPTERS = [
  {
    id: 'ch1',
    title: 'Chapter 1',
    subtitle: 'Creating the Robot Friends',
    chapterKey: 'Ch1',
    blocks: [
      { type: 'slot', slot_id: 'ch1-kitchen', order_index: 1, label: 'Jackie tippy-toeing into the kitchen — arms overflowing with treasures' },
      { type: 'text', content: 'One rainy Scottish morning, the rain tapped (pat-pat-patter) on the roof. Inside the cozy kitchen, Jackie Roo tippy-toed in, arms overflowing with treasures — a turquoise tin, an old bagpipe, a flower-speckled tea cozy, Grandma\'s woolly jumper, and shortbread tins going (clinkety-clink!) with every step.' },
      { type: 'slot', slot_id: 'ch1-building', order_index: 2, label: 'Mum and Jackie building the characters together on the kitchen table' },
      { type: 'text', content: '"Time for magic!" she declared. "Let\'s make robots!" Mum looked up from her iPad, coffee paused mid-sip. "What a brilliant idea, my clever girl!" Together they spread everything out on the kitchen table. Tools and tins and bits and bobs. And they built.' },
      { type: 'slot', slot_id: 'ch1-scotchbot', order_index: 3, label: 'Scotch Bot — turquoise body, golden medallion spinning (whizz-beep!)' },
      { type: 'text', content: 'From tins and springs and swirly things — (whizz-beep!) — Scotch Bot!' },
      { type: 'slot', slot_id: 'ch1-bagpipebot', order_index: 4, label: 'Bagpipe Bot — tartan kilt, tam o\'shanter flopping (toot-toot-wheeze!)' },
      { type: 'text', content: 'From tartan ribbons and a checkered hat — (toot-toot-wheeze!) — Bagpipe Bot!' },
      { type: 'slot', slot_id: 'ch1-tess', order_index: 5, label: 'Tea Cozy Tess curtsying — floral dress, spoon hands raised (ping-ping!)' },
      { type: 'text', content: 'From a flower-speckled cozy and two silver spoons — (ping-ping!) — Tea Cozy Tess!' },
      { type: 'slot', slot_id: 'ch1-woolywatt', order_index: 6, label: 'Woolie Watt — purple woolly jumper, wild orange wire hair (zip-zap!)' },
      { type: 'text', content: 'From Grandma\'s woolly jumper and a crackle of static — (zip-zap!) — Woolie Watt!' },
      { type: 'slot', slot_id: 'ch1-sam', order_index: 7, label: 'Shortbread Sam opening chest window — offering one to Jackie (clink-clank!)' },
      { type: 'text', content: 'From shortbread tins and a very neat bow tie — (clink-clank!) — Shortbread Sam!' },
      { type: 'slot', slot_id: 'ch1-five-characters', order_index: 8, label: 'All five finished tin toy characters lined up on the kitchen table' },
      { type: 'text', content: 'Five characters sat in a cheerful row. Still. Eyes closed. Waiting. Jackie looked at them for a long moment. Then she reached for her pouch. "Just a pinch of magic will do," she whispered.' },
      { type: 'slot', slot_id: 'ch1-signs-of-life', order_index: 9, label: 'The five robots on the counter — secret signs of life the moment Mum leaves the room' },
      { type: 'slot', slot_id: 'ch1-incantation', order_index: 10, label: 'Jackie kneeling on kitchen floor, glitter cascading from raised pan' },
      { type: 'text', content: "Jackie kneeled on the floor. She reached into her front pouch — deep, past the acorns and the bottle cap and the very important rock — and pulled out the glitter. She tipped it — and it cascaded down in a golden waterfall. She took a deep breath.\n\n'Boopity Bloppity Bloop...'\n\nNothing happened.\n\nShe tried again. Louder. Firmer. Eyes squeezed shut.\n\n'BLIPPAHDY! BLOPPAHDEE! BLOOP!!'" },
      { type: 'pageturn' },
      { type: 'slot', slot_id: 'ch1-reveal', order_index: 10, label: 'CHAPTER 1 REVEAL — kitchen floor quiet. Five still tin toys in a circle. Glitter pooling gold.' },
    ],
  },
  {
    id: 'ch2',
    title: 'Chapter 2',
    subtitle: 'The Oak Tree Adventure & Splattermath',
    chapterKey: 'Ch2',
    blocks: [
      { type: 'slot', slot_id: 'ch2-wagon', order_index: 11, label: 'Jackie pulling the red wagon through the back yard — five characters piled in' },
      { type: 'text', content: 'The back yard was perfect in the rain. Jackie pulled the red wagon through the wet grass, five characters piled in and holding on. She had one destination in mind.' },
      { type: 'slot', slot_id: 'ch2-oak-greeting', order_index: 12, label: 'Jackie pressing both palms flat against the ancient stump — face close, eyes closed' },
      { type: 'text', content: 'She pressed both palms flat against the bark. Face close. Eyes closed. "Hello," she said quietly. "I brought everyone." The stump said nothing. But something answered.' },
      { type: 'slot', slot_id: 'ch2-oak-pocket', order_index: 13, label: 'Jackie crouching at the base of the stump — reaching down to pick up a single glowing acorn' },
      { type: 'text', content: 'There — at the very base of the stump — a single acorn. Glowing amber. She picked it up with both hands. A quiet (tock) as it landed in her palm. She patted her pouch (pat-pat) and tucked it safely inside. She would keep it forever.' },
      { type: 'slot', slot_id: 'ch2-scotchbot-spots', order_index: 14, label: 'Scotch Bot frozen mid-wobble — golden medallion whirling (whizz-beep-BEEP!)' },
      { type: 'text', content: 'Scotch Bot had gone very still. His golden medallion was spinning. His eye had fixed on something magnificent. The Grand Puddle Grid. Centre lawn. Gleaming. (whizz-beep-BEEP!)\n\n"Professor Jackie Roo," he announced solemnly, "I believe we have a situation."' },
      { type: 'slot', slot_id: 'ch2-splashtermath', order_index: 15, label: 'SPLASHTERMATH — Scotch Bot' },
      { type: 'text', content: 'SPLASHTERMATH.\n\nScotch Bot. In. The puddle.\n(zing-zing-ZING!)' },
      { type: 'slot', slot_id: 'ch2-pitt-pattermath', order_index: 16, label: 'PITT PATTERMATH — Bagpipe Bot' },
      { type: 'text', content: 'PITT PATTERMATH.\n\nBagpipe Bot. Into the next puddle.\n(toot-toot-SPLOSH!)' },
      { type: 'slot', slot_id: 'ch2-scattermath', order_index: 17, label: 'SCATTERMATH — Woolie Watt' },
      { type: 'text', content: 'SCATTERMATH.\n\nWoolie Watt. Static and mud.\n(zip-zap-ZOOM!)' },
      { type: 'slot', slot_id: 'ch2-crashtermath', order_index: 18, label: 'CRASHTERMATH — Shortbread Sam' },
      { type: 'text', content: 'CRASHTERMATH.\n\nShortbread Sam. Personally affronted by physics.\n(clink-clank-CRASH!)' },
      { type: 'slot', slot_id: 'ch2-smattermath', order_index: 19, label: 'SMATTERMATH meets SPLATTERMATH — Jackie and Tess' },
      { type: 'text', content: 'SMATTERMATH!! SPLATTERMATH!!\n\nTea Cozy Tess and Jackie Roo. Together. Science cannot explain it.\n(ping-ping! boing-boing-BOUNCE!)' },
      { type: 'slot', slot_id: 'ch2-orchestra', order_index: 20, label: 'Jackie conducting the muddy orchestra — oak twig wand raised, all five characters mid-sound in the puddles' },
      { type: 'text', content: 'Jackie raised her oak twig wand. She rose on her tippy-toes. She conducted. The cheeky Scottish sun peeked through the clouds for just a moment — as if it wanted to watch.' },
      { type: 'pageturn' },
      { type: 'slot', slot_id: 'ch2-reveal', order_index: 21, label: 'CHAPTER 2 REVEAL — the stump in the rain. Five still tin toys propped around it.' },
    ],
  },
  {
    id: 'ch3',
    title: 'Chapter 3',
    subtitle: 'The Secret Rainbow Cave',
    chapterKey: 'Ch3',
    blocks: [
      { type: 'slot', slot_id: 'ch3-waterfall-picnic', order_index: 22, label: 'Picnic beside the waterfall — rainbow trout sandwiches, Tess ladling rainbow carrot soup' },
      { type: 'text', content: 'They picnicked beside the waterfall. Rainbow trout sandwiches. Rainbow chard. Tea Cozy Tess ladled rainbow carrot soup with great ceremony, steam curling up into the waterfall mist. Everyone agreed it was the finest picnic in the history of the back yard.' },
      { type: 'slot', slot_id: 'ch3-waterfall-dive', order_index: 23, label: 'Scotch Bot diving into the waterfall — rainbow bridge of light forming to the cave entrance' },
      { type: 'text', content: 'Scotch Bot stepped forward. He looked at the waterfall. He looked at Jackie. He looked at the waterfall again.\n\nAnd then — (plop!) — he stepped right in.\n\nHis golden glow radiated outward through the mist, and where it touched the droplets — a bridge. Shimmering. Arching. Rainbow.\n\n"Oh," said Jackie. And that was quite enough.' },
      { type: 'slot', slot_id: 'ch3-cave', order_index: 24, label: 'Rainbow cave interior — walls singing in every colour, Jackie twirling with oak twig wand' },
      { type: 'text', content: 'Inside the green shed — the Rainbow Cave — the walls sang in every colour. Red glowed warm. Orange tickled. Yellow sang happy. Green whispered peace. Blue cooled. Indigo dreamed. Violet sparkled mystery. Jackie twirled with her oak twig wand. The characters danced in the coloured light.' },
      { type: 'pageturn' },
      { type: 'slot', slot_id: 'ch3-birdbath-reveal', order_index: 25, label: 'CHAPTER 3 REVEAL — old stone bird bath. Scotch Bot face-down in the water, rainbow ribbon trailing. Four toys scattered on the damp grass.' },
    ],
  },
  {
    id: 'ch4',
    title: 'Chapter 4',
    subtitle: 'The Whispering Windship',
    chapterKey: 'Ch4',
    blocks: [
      { type: 'slot', slot_id: 'ch4-whistle', order_index: 26, label: 'Jackie finding the brass whistle among the rainbow pebbles' },
      { type: 'text', content: 'Among the rainbow pebbles — there. A brass whistle. Jackie held it up to the grey sky. Her eyes went enormous. Her oak twig wand was already tucked under her arm. She blew. (tweet-toot!)' },
      { type: 'slot', slot_id: 'ch4-windship', order_index: 27, label: 'The windship — the red wagon transformed, dragonfly-wing sails unfurling' },
      { type: 'text', content: 'The red wagon transformed. Dragonfly-wing sails unfurled from somewhere impossible. A rope ladder hung down. All five characters looked up in wonder. Jackie was already climbing.' },
      { type: 'slot', slot_id: 'ch4-cloud-castle', order_index: 28, label: 'The Cloud Castle — vast hall of dancing colours, the Cloud Keeper present, Jackie and characters in awe' },
      { type: 'text', content: 'The Cloud Castle was vast beyond imagining. Halls of dancing singing colour. The Cloud Keeper was a gentle whispering presence — more suggestion than shape. "You found the whistle," it said. "We\'ve been waiting." Everyone stood very still in the awe of it.' },
      { type: 'slot', slot_id: 'ch4-storm', order_index: 29, label: 'THE STORM KING BATTLE — Jackie at the wagon helm, wand raised, dark storm cloud above' },
      { type: 'text', content: 'Then the Storm King came. Dark. Enormous. Furious. Jackie gripped the helm. She raised her wand. The characters took their positions. The battle was magnificent and terrifying and over very quickly — because it was Jackie\'s back yard, and she knew every inch of it.' },
      { type: 'slot', slot_id: 'ch4-bottled-cloud', order_index: 30, label: 'The Cloud Keeper presenting the bottled cloud — Jackie holding it carefully, descending toward the yard at twilight' },
      { type: 'text', content: 'The Cloud Keeper offered a gift: a small glowing bottle. Inside — a bottled cloud that released a gentle (puff-puff) when you squeezed it softly. The characters hummed a lullaby. The windship descended toward the yard. The lights in the cottage glowed amber and warm.' },
      { type: 'pageturn' },
      { type: 'slot', slot_id: 'ch4-reveal', order_index: 31, label: 'CHAPTER 4 REVEAL — Jackie pulling red wagon in the rain. Dragonfly print tea towel as sail. Five tin toys inside.' },
      { type: 'slot', slot_id: 'ch4-shed-reveal', order_index: 32, label: 'CHAPTER 4 REVEAL — inside the green shed. Plugin fountain burbling. Soap bubbles sculpting into castle turret shapes. Five still inanimate toys propped along the counter.' },
    ],
  },
  {
    id: 'ch5',
    title: 'Chapter 5',
    subtitle: 'The Woolly Goalkeeper, Quack Bot & the Cleaning Fairy',
    chapterKey: 'Ch5',
    blocks: [
      { type: 'slot', slot_id: 'ch5-football-lineup', order_index: 33, label: 'Jackie and all five robots trooping across the back garden — two upturned terracotta pots as goalposts ahead' },
      { type: 'text', content: 'The back yard needed one more thing. A proper match. Jackie lined everyone up. Two upturned terracotta pots at the far end. She had a plan.' },
      { type: 'slot', slot_id: 'ch5-wooliewatt-knitting', order_index: 34, label: 'Woolie Watt sitting cross-legged on the damp grass, knitting needles flickering (click-click-klink!)' },
      { type: 'text', content: 'Woolie Watt sat cross-legged in the damp grass. His knitting needles flickered. A lumpy teal-and-gold wool ball grew in his lap. (click-click-klink!) "The official match ball," he announced. No one argued.' },
      { type: 'slot', slot_id: 'ch5-scotchbot-goalkeeper', order_index: 35, label: 'Scotch Bot standing proudly between the terracotta pot goalposts — left eye swirling red, right eye gleaming gold' },
      { type: 'text', content: 'Scotch Bot took his position between the terracotta pots. Feet planted wide. Arms spread. Left eye swirling red. Right eye gleaming gold. He was, he informed everyone, completely unbeatable.' },
      { type: 'slot', slot_id: 'ch5-eye-lost', order_index: 36, label: 'Jackie kicking the wool ball — it hits Scotch Bot\'s face, his swirly eye flying out, everyone frozen' },
      { type: 'text', content: 'Jackie ran up. She kicked.\n\nThe wool ball sailed through the air.\n\nAnd — (BONK!) — it hit Scotch Bot directly in the face.\n\nOne swirly red eye flew out in a magnificent arc and disappeared into the long wet grass.\n\nEveryone froze.\n\n"Oh no," said Jackie.' },
      { type: 'slot', slot_id: 'ch5-bagpipebot-recycling', order_index: 37, label: 'Bagpipe Bot at the recycling bin — holding up a dark glass bottle with a gold wax seal with great dignity' },
      { type: 'text', content: 'Bagpipe Bot marched to the recycling bin with great purpose. He reached in. He held up a dark glass bottle with a gold wax seal.\n\n(toot-toot.)\n\nHe said nothing more. He didn\'t need to.' },
      { type: 'slot', slot_id: 'ch5-jackie-fixes-eye', order_index: 38, label: 'Jackie on her very tippy-toes, pressing the gold wax seal onto Scotch Bot\'s empty eye socket — Scotch Bot deeply moved' },
      { type: 'text', content: 'Jackie stood on her very tippy-toes. Tongue-tip out in concentration. She pressed the gold wax seal — gently, carefully — onto Scotch Bot\'s empty socket.\n\nScotch Bot blinked. His medallion turned slowly.\n\n(whizz... beep.)\n\nHe looked at Jackie for a long moment.\n\n"Professor Jackie Roo," he said, very quietly. "Thank you."' },
      { type: 'slot', slot_id: 'ch5-tess-finds-eye', order_index: 39, label: 'Tea Cozy Tess holding up the woolly ball triumphantly — Scotch Bot\'s red spiral eye pressed into the wool, staring out' },
      { type: 'text', content: 'Tea Cozy Tess had been very quiet. Now she held up the teal-and-gold wool ball with both spoon-hands.\n\nScotch Bot\'s red spiral eye stared out from the centre, perfectly snug, looking rather pleased with itself.\n\n(ting-a-ting-ding!)\n\n"I found it," said Tess simply.\n\nEveryone cheered.' },
      { type: 'slot', slot_id: 'ch5-flower-picking', order_index: 40, label: 'Jackie kneeling picking wildflowers — Mum\'s face visible through the warm cottage window, watching quietly' },
      { type: 'text', content: 'Jackie knelt in the rain-soaked grass. She picked wildflowers. One by one. She didn\'t notice the warm light in the cottage window. She didn\'t notice the face behind the glass. Watching. Quietly. Not interrupting.' },
      { type: 'slot', slot_id: 'ch5-puddle-parade', order_index: 41, label: 'Jackie and all five characters taking turns jumping in the giant muddy puddle — flower held aloft, sound word floating above each' },
      { type: 'text', content: 'One last thing.\n\nThe big puddle.\n\n(SPLOSH!) Jackie.\n(ZING-ZING!) Scotch Bot.\n(TOOT-SPLOSH!) Bagpipe Bot.\n(ZIP-ZAP!) Woolie Watt.\n(CLINK-CRASH!) Shortbread Sam.\n(PING-BOUNCE!) Tea Cozy Tess.\n\nEach one holding a wildflower. Each one glorious.' },
      { type: 'slot', slot_id: 'ch5-doorway-handoff', order_index: 42, label: 'Jackie handing the muddy robot bundle and wildflower bouquet to Mum at the yellow door' },
      { type: 'text', content: 'The yellow door opened. Jackie held out the muddy bundle of robots and the wildflower bouquet.\n\n"For you," she said.\n\nMum took them. Both. Without hesitation.\n\n"They\'re perfect," she said. And she meant all of it.' },
      { type: 'slot', slot_id: 'ch5-cleaning-fairy', order_index: 43, label: 'Mum saying "I wish there was a cleaning fairy" — glasses askew, Jackie looking up with enormous eyes' },
      { type: 'text', content: 'Mum surveyed the bathroom. Bubbles on the ceiling. Mud on the tiles. Glitter in the grout. Her glasses were askew. Very quietly, under her breath, she said:\n\n"I wish there was a cleaning fairy."\n\nJackie looked up. Her eyes went enormous.\n\n"Whats a cleaning fairy?"\n\nAn idea arrived.' },
      { type: 'slot', slot_id: 'ch5-quackbot', order_index: 44, label: 'Jackie holding Quack Bot triumphantly — Mum laughing properly, rainbow bubbles everywhere' },
      { type: 'text', content: 'Jackie reached into her pouch. She pressed Scotch Bot\'s spare swirly eye onto the rubber duck. Then she held it up with both hands.\n\n"Mum. Meet Quack Bot."\n\nMum laughed. Properly. The kind that takes over.\n\nQuack Bot said nothing. He was a rubber duck. But he had one very fine swirly eye.' },
      { type: 'pageturn' },
      { type: 'slot', slot_id: 'ch5-reveal', order_index: 45, label: 'CHAPTER 5 REVEAL — five clean tin toys on the edge of the tub. A rubber duck with one googly eye. A stick on the floor. Glitter in the grout.' },
    ],
  },
  {
    id: 'finale',
    title: 'Finale',
    subtitle: 'Wordless',
    chapterKey: 'Finale',
    blocks: [
      { type: 'slot', slot_id: 'finale-rocking', order_index: 46, label: 'Mum rocking Jackie in the armchair — Quack Bot hugged tight, five tin toys on the windowsill, acorn glowing softly, Mums & Buds sign faintly visible' },
      { type: 'slot', slot_id: 'finale-backyard', order_index: 47, label: 'FINAL IMAGE — the whole back yard from above, rain still falling. Every adventure mapped. No characters. No words. Just the yard. It was here the whole time.' },
    ],
  },
];