export const SLOT_CONFIG = [
  { slot_id: 'ch1-1',            chapter: 'Ch1',    order_index: 1,  label: 'Jackie tippy-toeing into kitchen with arms full of treasures — turquoise tin, bagpipe, tea cozy, woolly sweater, shortbread tins' },
  { slot_id: 'ch1-2',            chapter: 'Ch1',    order_index: 2,  label: 'Mum and Jackie crafting Scotch Bot — polishing golden medallion, adding bell, swirly eyes glowing' },
  { slot_id: 'ch1-scotch',       chapter: 'Ch1',    order_index: 3,  label: 'Scotch Bot birth panel — zing-zing!' },
  { slot_id: 'ch1-bagpipe',      chapter: 'Ch1',    order_index: 4,  label: 'Bagpipe Bot birth panel — toot-toot-wheeze!' },
  { slot_id: 'ch1-tess',         chapter: 'Ch1',    order_index: 5,  label: 'Tea Cozy Tess birth panel — ping!' },
  { slot_id: 'ch1-woolie',       chapter: 'Ch1',    order_index: 6,  label: 'Woolie Watt birth panel — zip-zap!' },
  { slot_id: 'ch1-sam',          chapter: 'Ch1',    order_index: 7,  label: 'Shortbread Sam birth panel — munch-munch-happy-lunch!' },
  { slot_id: 'ch1-row-before',   chapter: 'Ch1',    order_index: 8,  label: 'PAGE TURN (1 of 2) — Mum and Jackie admiring all five robots in a cheerful row, stormy rain outside, robots perfectly still' },
  { slot_id: 'ch1-row-after',    chapter: 'Ch1',    order_index: 9,  label: 'PAGE TURN (2 of 2) — Robots ERUPT the moment Mum leaves the room — sparks flying, Woolie Watt crackling, Tess steaming, Jackie spinning' },
  { slot_id: 'ch2-wagon',        chapter: 'Ch2',    order_index: 10, label: 'Jackie pulling red wagon through misty Scottish park toward the wise old oak tree' },
  { slot_id: 'ch2-puddle',       chapter: 'Ch2',    order_index: 11, label: 'Scotch Bot spotting the muddy puddle — golden medallion whirling, magnificent SPLISH-SPLASH' },
  { slot_id: 'ch2-orchestra',    chapter: 'Ch2',    order_index: 12, label: 'All robots and Jackie in the muddy puddle — Jackie conducting with stick wand, golden peek-a-boo sun' },
  { slot_id: 'ch2-oak',          chapter: 'Ch2',    order_index: 13, label: 'Jackie pressing hands on the wise old oak tree — glowing acorn lantern, puddle reflection' },
  { slot_id: 'ch3-bandit',       chapter: 'Ch3',    order_index: 14, label: 'Scotch Bot with cheeky muddy bandit mask — Jackie secretly packing surprise picnic with rainbow trout sandwiches and Swiss chard' },
  { slot_id: 'ch3-cave',         chapter: 'Ch3',    order_index: 15, label: 'Rainbow cave interior — singing colours, Jackie twirling with wand, robots dancing' },
  { slot_id: 'ch3-picnic',       chapter: 'Ch3',    order_index: 16, label: 'Rainbow cave picnic feast — Tess ladling rainbow carrot soup, everyone mid-feast and laughing' },
  { slot_id: 'ch4-windship',     chapter: 'Ch4',    order_index: 17, label: 'Jackie blowing brass whistle — dragonfly-wing windship hovering above in the mist' },
  { slot_id: 'ch4-storm',        chapter: 'Ch4',    order_index: 18, label: 'Transformed playground ship soaring — dramatic Storm King battle, robots defending' },
  { slot_id: 'ch4-return',       chapter: 'Ch4',    order_index: 19, label: 'Ship descending to playground at twilight — bottled cloud, robots humming lullaby, sleepy Jackie' },
  { slot_id: 'ch5-march',        chapter: 'Ch5',    order_index: 20, label: 'Jackie and all five robots trooping across the back garden — terracotta pot goalposts ahead' },
  { slot_id: 'ch5-woolie-knits', chapter: 'Ch5',    order_index: 21, label: 'Woolie Watt knitting the teal-and-gold wool ball — sparks from orange wire hair — click-click-klink!' },
  { slot_id: 'ch5-goalkeeper',   chapter: 'Ch5',    order_index: 22, label: 'Scotch Bot the unbeatable goalkeeper — feet planted, arms spread, left eye swirling, chin lifted' },
  { slot_id: 'ch5-eye-lost',     chapter: 'Ch5',    order_index: 23, label: 'Commotion! Scotch Bot standing still, one eye socket empty — everyone frozen, looking at the grass' },
  { slot_id: 'ch5-bagpipe-bottle', chapter: 'Ch5', order_index: 24, label: 'Bagpipe Bot at the recycling bin — holding up dark glass bottle with great dignity' },
  { slot_id: 'ch5-eye-fixed',    chapter: 'Ch5',    order_index: 25, label: 'Jackie on very tippy-toes, tongue out in concentration, pressing gold seal onto Scotch Bot\'s eye socket' },
  { slot_id: 'ch5-tess-finds',   chapter: 'Ch5',    order_index: 26, label: 'Tea Cozy Tess holding up the woolly ball — Scotch Bot\'s red spiral eye embedded in it. Tess mid-laugh — ting-a-ting-ding!' },
  { slot_id: 'ch5-pouch',        chapter: 'Ch5',    order_index: 27, label: 'Jackie peeling the red spiral eye off the wool ball, tucking it into her kangaroo pouch' },
  { slot_id: 'ch5-flowers',      chapter: 'Ch5',    order_index: 28, label: 'Jackie picking wildflowers — Mum\'s face visible through the warm cottage window, watching with a tender smile' },
  { slot_id: 'ch5-puddle-grid',  chapter: 'Ch5',    order_index: 29, label: 'Six-panel puddle jump grid — each character taking their turn in the pouring rain' },
  { slot_id: 'ch5-doorway',      chapter: 'Ch5',    order_index: 30, label: 'Jackie handing muddy robot bundle to Mum — treasure basket glowing on entryway floor, yellow door open behind' },
  { slot_id: 'ch5-cleaning-fairy', chapter: 'Ch5', order_index: 31, label: "What's a cleaning fairy? — yellow door, Jackie looking up, treasure basket glowing on the floor" },
  { slot_id: 'ch5-quackbot',     chapter: 'Ch5',    order_index: 32, label: 'Jackie holding Quack Bot triumphantly — Mum laughing beside the tub, rainbow bubbles everywhere' },
  { slot_id: 'finale',           chapter: 'Finale', order_index: 33, label: 'Mum rocking Jackie in the armchair — Quack Bot hugged tight, all five robots on the windowsill in the rain watching over them' },
];

export const CHAPTER_META = {
  Ch1:    { number: 1, title: 'Chapter 1', subtitle: 'Creating the Robot Friends' },
  Ch2:    { number: 2, title: 'Chapter 2', subtitle: 'The Oak Tree Adventure' },
  Ch3:    { number: 3, title: 'Chapter 3', subtitle: 'The Journey to the Secret Rainbow Cave' },
  Ch4:    { number: 4, title: 'Chapter 4', subtitle: 'The Whispering Windship' },
  Ch5:    { number: 5, title: 'Chapter 5', subtitle: 'The Woolly Goalkeeper' },
  Finale: { number: 6, title: 'Finale',    subtitle: 'Wordless Rocking Scene' },
};